### ISSUE TITLE
Include npm package listing

### ISSUE THREAD

**Issue by hugeblank** [CSSDC/ChatApp#2]
Sure I could run into the error for each package and install it, but it's good to have ~~the `packages.json` (I think that's what it's called)~~ in the repo. Also I'm lazy so no to the first option.

EDIT: I don't know what it's called.

**Comment by xseano** [comment]
Thanks, all dependencies are listed in the `package.json`, which was added in commit https://github.com/CSSDC/ChatApp/commit/7dee91955a1b8207070a3de6ae3df09553cd59c5
